sudo: false

dist: xenial

services: mysql

language: php

addons:
  apt:
    packages:
    - libwebp-dev

php:
    - 7.2

env:
    global:
        - TMPDIR=/tmp
        - COVERALLS_PARALLEL=true
    matrix:
        - WP_VERSION=4.9.8 WP_MULTISITE=0 
        - WP_VERSION=4.9.8 WP_MULTISITE=1
        - WP_VERSION=latest WP_MULTISITE=0
        - WP_VERSION=latest WP_MULTISITE=1

matrix:
    include:
    - php: 5.6
      env: WP_VERSION=4.9.8 WP_MULTISITE=0 PREFER_LOWEST="--prefer-lowest --prefer-stable" COVERAGE=1
      before_install: skip
      before_script:
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        - composer update $PREFER_LOWEST --prefer-source
        - if [ "$COVERAGE" == 1 ]; then composer require --dev 'satooshi/php-coveralls:1.0.*'; fi
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=0 COVERAGE=1
      before_install:
        - phpenv config-rm xdebug.ini
        - yes '' | pecl install pcov
        # Install imagick PHP extension
        - pear config-set preferred_state beta
        - pecl channel-update pecl.php.net
        - yes '' | pecl install imagick
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=1 COVERAGE=1

before_install:
    # phpenv config-add myconfig.ini --with-webp-dir
    - phpenv config-rm xdebug.ini
    - yes '' | pecl install pcov

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer update $PREFER_LOWEST --prefer-source
    - composer require --dev 'pcov/clobber:^2.0'
    - vendor/bin/pcov clobber
    - if [ "$COVERAGE" == 1 ]; then composer require --dev 'satooshi/php-coveralls:1.0.*'; fi

script:
    - if [ "$COVERAGE" == 1 ]; then mkdir -p build/logs; vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml --verbose; else vendor/phpunit/phpunit/phpunit -c phpunit-nocover.xml --verbose; fi

after_success:
    - if [ "$COVERAGE" == 1 ]; then bash <(curl -s https://codecov.io/bash) -Z; fi
    - if [ "$COVERAGE" == 1 ]; then vendor/bin/coveralls -v; fi

notifications:
  webhooks:
    # https://docs.coveralls.io/parallel-build-webhook
    - 'https://coveralls.io/webhook'
